### Create Article
POST localhost:8081/article/create
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "title": "WWWW",
  "content": "Article",
  "categoryIds": [
    1
  ],
  "description": "DDDD",
  "imageId": 1,
  "regionId": 1,
  "sectionIds": [
    1
  ]
}

### Update Article
PUT localhost:8081/article/update/9fb4ae59-4d0b-49ec-befb-fd37c7c2e55a
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "title": "IIII",
  "content": "EEEE",
  "categoryIds": [
    1
  ],
  "description": "DDXXXDD",
  "imageId": 1,
  "regionId": 1,
  "sectionIds": [
    1
  ]
}

### Delete Article By Article ID
DELETE localhost:8081/article/delete/11ec45c6-2ba9-410c-87ad-c9fd14b0a774
Authorization: Basic UVFROjAwMDA=


### Change Article Status By Article Id
PUT localhost:8081/article/change-status
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "articleId": "11ec45c6-2ba9-410c-87ad-c9fd14b0a774",
  "status": "PUBLISHED"
}

### Get Articles By Section ID
GET localhost:8081/article/get-by/sectionId?page=1&size=1
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "sectionId": 1
}

### Get Last 12 published Article except given id list ordered_by_created_date
POST localhost:8081/article/last12-except
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "idList": [
    "11ec45c6-2ba9-410c-87ad-c9fd14b0a774"
  ]
}

### Get Articles By Category ID
GET localhost:8081/article/get-by/category?page=1&size=1
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "categoryId": 1
}

### Get Articles By Region Id
POST localhost:8081/article/get-by/region-id
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "regionId": 1
}

### Get Article By Article Id
GET localhost:8081/article/get-by-id/9fb4ae59-4d0b-49ec-befb-fd37c7c2e55a
Authorization: Basic UVFROjAwMDA=

### Get Articles By Tag Name
POST localhost:8081/article/get-by/tag-name
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "name": "TAG"
}
