### Create Section
POST localhost:8080/section
Content-Type: application/json

{
  "key": "fj",
  "nameEn": "Dalzarb",
  "nameRu": "човутоу",
  "nameUz": "Dolzarb",
  "orderNumber": 1
}

### Update Section By Id
PUT localhost:8080/section/1
Content-Type: application/json

{
  "orderNumber": 2,
  "nameUz": "Akademik",
  "nameRu": "тувуштвуш",
  "nameEn": "Academic",
  "key": "Ac"
}

### Delete Section By Id
DELETE localhost:8080/section/1

### Get Section List By Pagination
GET localhost:8080/section/list?page=1&size=5