### Get Profile By Id
GET localhost:8080/profile/by-id/1

### Update profile
PUT localhost:8080/profile?id=1
Content-Type: application/json

{
  "username": "AlijonBek",
  "password": "123",
  "name": "Alijon",
  "surname": "Alijonov"
}

### Update Profile By Details
PUT localhost:8080/profile/update-detail/1
Content-Type: application/json

{
  "name": "Alijon"
}

### Get all profiles by Pagination
GET localhost:8080/profile/list?page=1&size=8

### Delete Profile By Id
DELETE localhost:8080/profile?id=1

### Update Password
PUT localhost:8080/profile/password/6
Content-Type: application/json

{
  "oldPassword": "1111",
  "newPassword": "0000"
}

### Get profiles by filter
GET localhost:8080/profile/filter?page=1&size=3&query=Islom
