### Registration
POST localhost:8080/auth/register
Content-Type: application/json

{
  "surname": "Azizov",
  "name": "Aziz",
  "password": "0000",
  "username": "Znjnx",
  "email": "qiyomiddinjumabekov1@gmail.com"
}

### Confirm Profile
POST localhost:8080/auth/confirm
Content-Type: application/json

{
  "email": "qiyomiddinjumabekov1@gmail.com",
  "code": "58887"
}

### Resent Code
POST localhost:8080/auth/resent/qiyomiddinjumabekov1@gmail.com

### Login Profile
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "Znjnx",
  "password": "0000"
}