### Create Tag
POST localhost:8081/tag/create
Authorization: Basic UVFROjAwMDA=
Content-Type: application/json

{
  "articleId": "9fb4ae59-4d0b-49ec-befb-fd37c7c2e55a",
  "name": "TAG"
}

### Get All Tags
GET localhost:8081/tag/list
Authorization: Basic UVFROjAwMDA=
